name: Send Discord Webhook
description: Send a Discord webhook message with components v2 for a Geode mod release notification.

inputs:
  webhook-url:
    description: "The webhook URL to send the message to"
    required: true

  mod-json-path:
    description: "Relative path to the mod's `mod.json` file. Defaults to root mod.json."
    required: false
    default: ""

  changelog:
    description: "Multi-line changelog text to include in the message."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download action code
      shell: bash
      run: git clone https://github.com/BlueWitherer/geode-mod-webhook.git

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Send Discord Webhook
      shell: bash
      run: node geode-mod-webhook/src/index.js
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        MOD_JSON_PATH: ${{ inputs.mod-json-path }}
        CHANGELOG_TEXT: ${{ inputs.changelog }}
